
name: Testing
'on':
  push:
    branches:
      - testing
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: 
      name: Testing
      url: https://quizmaster-testing-ee900.firebaseapp.com/
    steps:
      - uses: actions/checkout@v4
      - run: 'npm ci && npm run build'
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_QUIZMASTER_C66A2 }}'
          channelId: live
          target: testing
          projectId: quizmaster-c66a2
